apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: gcp-storage
  gcePersistentDisk:
    pdName: my-gce-disk
    fsType: ext4
