apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-premium
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-rwo
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: my-premium-pv
